### ISSUE TITLE
Question: Can this be made for Portal 2?

### ISSUE THREAD

**Issue by FrozenDragon0** [saul/csgo-cvar-unhide#14]
Hello I only recently discovered this and was wondering if there could be a version made that works for Portal 2?

EDIT: I read a reddit post that this did work for Portal 2 but the game has since been updated recently.

**Comment by saul** [comment]
It should still work with Portal 2. Have you tried it?

**Comment by FrozenDragon0** [comment]
@saul Yes I have tried it and it doesn't work. I suspect the recent updates portal 2 has had most likely broke it.

EDIT: Attempting to load the plugin manually in the console will give this error: 
Could not get IServerPluginCallbacks interface from plugin "cvar-unhide"Unable to load plugin "cvar-unhide"

**Comment by saul** [comment]
You're right - I've just tried it and it doesn't work. The Portal 2 and CSGO engines are quite different, so it needs to be compiled against the (unofficial) Portal 2 SDK.

Try this: [addons.zip](https://github.com/saul/csgo-cvar-unhide/files/6096152/addons.zip)

**Comment by FrozenDragon0** [comment]
@saul Still doesn't work.

Same error: Could not get IServerPluginCallbacks interface from plugin "cvar-unhide.dll"Unable to load plugin "cvar-unhide.dll"

Having that DLL in apparently caused a side of effect of my game zooming in everytime I paused and unpaused the game.

**Comment by saul** [comment]
Are you running on Windows? The ZIP in my previous comment definitely works on my machine - can you double check that you're extracting it to the right place? `portal2/addons/cvar-unhide.dll` should have a 'Last modified' date of yesterday.

**Comment by FrozenDragon0** [comment]
It's definitely in the right place. Yes I am running Windows.

**Comment by saul** [comment]
Can you try using these binaries - they've just been built with GitHub Actions:
https://github.com/saul/csgo-cvar-unhide/suites/2197626435/artifacts/45352692

**Comment by FrozenDragon0** [comment]
@saul Still the same error.

**Comment by FrozenDragon0** [comment]
Oh hang on now it works. Apparently -insecure is still needed on Portal 2 despite VAC not being enabled for Portal 2.

EDIT: Hidden commands are now showing however apparently there is one command called paintallsurfaces but It does not seem to be working/showing up.

EDIT 2: Is there a way to view a whole list of all the hidden commands Portal 2 has? It's impossible to see all the commands in console as it won't let you scroll up all the way.

**Comment by saul** [comment]
You can use `con_logfile output.log` to redirect all console output to a file. Then after you `cvarlist_all` you can open `output.log` to see the full output.

See here for the full cvar list: https://gist.github.com/saul/ccebb64c2ac96d5cd5c97c17b2beabb8

Search for "devonly" and "hidden"

**Comment by saul** [comment]
Closing this off - Portal 2 binaries now available: https://github.com/saul/cvar-unhide/releases/tag/v20210307.30
