### ISSUE TITLE
Don't force -insecure on dedicated server

### ISSUE THREAD

**Issue by BeepIsla** [saul/csgo-cvar-unhide#18]
Hey, I never had issues because my localhost testing server runs in insecure but now that I wanted to use this on a secure server I am running into the insecure-safeguard. I understand having this for clients but servers are allowed to use addons, so I am requesting either the addon to automatically detect if it is running as a client/server or maybe have an additional command line option to bypass the insecure check.

**Comment by saul** [comment]
Fixed in https://github.com/saul/cvar-unhide/releases/tag/v20210313.43
