### ISSUE TITLE
Linux ubuntu 18.04 build doesn't seem to work

### ISSUE THREAD

**Issue by schen96** [saul/csgo-cvar-unhide#20]
I put it into csgo folder and the commands does not show up in the console.

My OS is ubuntu 18.04

**Comment by saul** [comment]
Hi - please can you paste the full console logs?

**Comment by Bo98** [comment]
I've got a similar issue. The console only showed a generic "failed to load" error, but I managed to get past that by doing `patchelf --replace-needed hl2sdk/lib/linux/libtier0.so libtier0.so cvar-unhide.so`.

The new error now is `undefined symbol: g_pCVar`.

**Comment by saul** [comment]
Released as https://github.com/saul/cvar-unhide/releases/tag/v20220328.45
