### ISSUE TITLE
CS:GO crashes

### ISSUE THREAD

**Issue by armync** [saul/csgo-cvar-unhide#24]
Using command `cvarlist_all` results in a crash.

Known working game version (as reference):

```
Protocol version 13844 [1519/1519]
Exe version 1.38.4.4 (csgo)
Exe build: 10:44:18 Sep 30 2022 (8598) (730)
```

**Comment by saul** [comment]
[v20221026.47](https://github.com/saul/cvar-unhide/releases/tag/v20221026.47) just released
