### ISSUE TITLE
Counter-Strike 2 compatibility

### ISSUE THREAD

**Issue by armync** [saul/csgo-cvar-unhide#29]
Hey there, some days ago Valve's Counter-Strike 2 was launched for most players in an open beta. Is there a compatibility for this game or so, any plan to create it?

Current path: \steamapps\common\Counter-Strike Global Offensive\game\csgo

**Comment by saul** [comment]
Hi - yes please see [cvar-unhide-s2](https://github.com/saul/cvar-unhide-s2).

Let me know how it goes - any issues please open an issue in that repo.
