### ISSUE TITLE
Not working on current CS:GO

### ISSUE THREAD

**Issue by ghost** [saul/csgo-cvar-unhide#4]
Placed the file in addons and launched the game with -insecure. Also tried to load the plugin manually:

> ] plugin_load cvar-unhide
> Unable to load plugin "cvar-unhide"
> Unable to load plugin "cvar-unhide"
> ] plugin_load cvar-unhide.dll
> Unable to load plugin "cvar-unhide.dll"
> Unable to load plugin "cvar-unhide.dll"
> ] plugin_load addons/cvar-unhide
> Unable to load plugin "addons/cvar-unhide"
> Unable to load plugin "addons/cvar-unhide"
> ] plugin_load addons/cvar-unhide.dll
> Unable to load plugin "addons/cvar-unhide.dll"
> Unable to load plugin "addons/cvar-unhide.dll"

**Comment by saul** [comment]
Can you paste a screenshot of what's inside your `$STEAM\steamapps\common\Counter-Strike Global Offensive\csgo\addons` folder please.
