### ISSUE TITLE
Port on Linux

### ISSUE THREAD

**Issue by SimoleS** [saul/csgo-cvar-unhide#5]
Hello is possible somehow get this running on linux CSGO server ? 
Thank you

**Comment by saul** [comment]
Yes it's definitely possible, but you'd have to compile the plugin from source yourself. I don't have time at the moment to do this, sorry.

**Comment by saul** [comment]
Linux binaries are now available for csgo: https://github.com/saul/cvar-unhide/releases/tag/v20210307.30
